name: Sonar Scanner CLI

on:
  push:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          sudo chmod +x /opt/sonar-scanner/bin/sonar-scanner

      - name: Run Scan
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=themiddlecat_Notes \
            -Dsonar.organization=themiddlecat \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=src \
            -Dsonar.java.binaries=. \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
